// templates/frontend/react-app/src/components/bootstrap/CustomDropdown.tsx
import Dropdown from 'react-bootstrap/Dropdown';
import {customDropdownProps} from "@/props/bootstrap/customDropdown";


const CustomDropdown = (props: customDropdownProps) => {
    return (
        <>
            <Dropdown className={props.customClassDropdown}>
                <Dropdown.Toggle variant={props.variant} id={props.id} className={props.customClassDropdownToggle}>
                    {props.title}
                </Dropdown.Toggle>
                <Dropdown.Menu className={props.customClassMenu}>
                    {props.listMenu && props.listMenu.map((item) => (
                        <Dropdown.Item className={props.customClassMenuItem} key={item.id} href={item.link}>{item.title}</Dropdown.Item>
                    ))}
                </Dropdown.Menu>
            </Dropdown>
        </>
    )
}

export default CustomDropdown

// templates/frontend/vue-app/src/components/elementPlus/customDropdown.vue
<template>
  <el-dropdown :placement="props.placement" :class="customClassWrapperDropdown">
    <custom-button :title-btn="titleBtn" :custom-class-btn="customClassBtn" />
    <template #dropdown>
      <el-dropdown-menu :class="customClassMenu">
        <el-dropdown-item :class="customClassItem" v-for="item in dropdownItem" :key="item.id">
          <custom-button v-if="item.link" :custom-class-btn="customClassLinkDropdown" :href-btn="item.link" :title-btn="item.title" />
          <template v-else>
            {{ item.title }}
          </template>
        </el-dropdown-item>
      </el-dropdown-menu>
    </template>
  </el-dropdown>
</template>

<script setup lang="ts">
import { customDropdownProps } from "@/props/elementPlus/customDropdown.ts";
import CustomButton from "@/components/customButton.vue";
import { customButtonProps } from "@/props/elementPlus/customButton.ts";

const props = defineProps({
  ...customDropdownProps,
  ...customButtonProps
})

</script>
